Update of printing chapters reflecting modifications and additions of smb.conf parameters. Also included is a "first ever" short description of the "VampireDriverFunctions" shell script which helps to transfer printer drivers "en masse" from one (NT/Samba) to another (NT/Samba) print server.
Also fixed a few mismatching tags in printer_driver2.xml which lead to
the rendering skippint some pages (tested on Sunday when SF was still
online).

Sorry, I could not verify if it still compiles to PDF, since sourceforge
isnt accsssible (the make attempts to fetch a file from there and freaks
out with

   compilation error: file xslt/latex.xsl line 5 element import
   xsl:import : unable to load http://db2latex.sourceforge.net/xsl/docbook.xsl
   make: *** [howto.tex] Error 5